name: jahitin

services:
  jahitin_db:
    image: postgres:15-alpine
    container_name: jahitin_db
    ports:
      - "${DB_EXPOSE_PORT}:${DB_PORT}"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./database/volume:/var/lib/postgresql/data
    networks:
      - jahitin-network

  jahitin_be:
    build:
      context: .
      dockerfile: Dockerfile
    image: mirzarama27/jahitin-be:latest
    container_name: jahitin_be
    env_file:
      - .env
    expose:
      - "${APP_PORT}"
    depends_on:
      - jahitin_db
    networks:
      - jahitin-network
      - main-network

networks:
  jahitin-network:
    external: true

  main-network:
    external: true
