// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clothes_category.sql

package jahitin_be_db

import (
	"context"
)

const listClothesCategories = `-- name: ListClothesCategories :many
SELECT
    id, name, created_at
FROM
    clothes_categories
ORDER BY
    name ASC
`

func (q *Queries) ListClothesCategories(ctx context.Context) ([]ClothesCategory, error) {
	rows, err := q.db.QueryContext(ctx, listClothesCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClothesCategory{}
	for rows.Next() {
		var i ClothesCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedClothesCategories = `-- name: SeedClothesCategories :many
INSERT INTO
    clothes_categories (name)
VALUES
    ('Kaos'),
    ('Kebaya'),
    ('Baju Anak'),
    ('Jas'),
    ('Jaket'),
    ('Seragam'),
    ('Kemeja'),
    ('Celana'),
    ('Rok'),
    ('Gaun'),
    ('Gamis') RETURNING id, name, created_at
`

func (q *Queries) SeedClothesCategories(ctx context.Context) ([]ClothesCategory, error) {
	rows, err := q.db.QueryContext(ctx, seedClothesCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClothesCategory{}
	for rows.Next() {
		var i ClothesCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
