// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package jahitin_be_db

import (
	"context"
	"database/sql"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    name, user_id, phone, notes, contact_key, country_code, formatted_phone
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, name, phone, notes, updated_at, created_at, contact_key, country_code, formatted_phone
`

type CreateCustomerParams struct {
	Name           string         `json:"name"`
	UserID         int64          `json:"user_id"`
	Phone          sql.NullString `json:"phone"`
	Notes          sql.NullString `json:"notes"`
	ContactKey     sql.NullString `json:"contact_key"`
	CountryCode    sql.NullString `json:"country_code"`
	FormattedPhone sql.NullString `json:"formatted_phone"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.Name,
		arg.UserID,
		arg.Phone,
		arg.Notes,
		arg.ContactKey,
		arg.CountryCode,
		arg.FormattedPhone,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Notes,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.ContactKey,
		&i.CountryCode,
		&i.FormattedPhone,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, user_id, name, phone, notes, updated_at, created_at, contact_key, country_code, formatted_phone FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Notes,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.ContactKey,
		&i.CountryCode,
		&i.FormattedPhone,
	)
	return i, err
}

const getCustomerByUserIDAndPhone = `-- name: GetCustomerByUserIDAndPhone :one
SELECT id, user_id, name, phone, notes, updated_at, created_at, contact_key, country_code, formatted_phone FROM customers
WHERE user_id = $1 AND formatted_phone = $2
LIMIT 1
`

type GetCustomerByUserIDAndPhoneParams struct {
	UserID         int64          `json:"user_id"`
	FormattedPhone sql.NullString `json:"formatted_phone"`
}

func (q *Queries) GetCustomerByUserIDAndPhone(ctx context.Context, arg GetCustomerByUserIDAndPhoneParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByUserIDAndPhone, arg.UserID, arg.FormattedPhone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Notes,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.ContactKey,
		&i.CountryCode,
		&i.FormattedPhone,
	)
	return i, err
}

const listCustomersByUserID = `-- name: ListCustomersByUserID :many
SELECT id, user_id, name, phone, notes, updated_at, created_at, contact_key, country_code, formatted_phone FROM customers
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCustomersByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCustomersByUserID(ctx context.Context, arg ListCustomersByUserIDParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomersByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.Notes,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.ContactKey,
			&i.CountryCode,
			&i.FormattedPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersByUserIDAndName = `-- name: ListCustomersByUserIDAndName :many
SELECT id, user_id, name, phone, notes, updated_at, created_at, contact_key, country_code, formatted_phone FROM customers
WHERE user_id = $1 AND name ILIKE '%' || $2 || '%'
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListCustomersByUserIDAndNameParams struct {
	UserID  int64          `json:"user_id"`
	Column2 sql.NullString `json:"column_2"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) ListCustomersByUserIDAndName(ctx context.Context, arg ListCustomersByUserIDAndNameParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomersByUserIDAndName,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.Notes,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.ContactKey,
			&i.CountryCode,
			&i.FormattedPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerNotes = `-- name: UpdateCustomerNotes :one
UPDATE customers
SET notes = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, phone, notes, updated_at, created_at, contact_key, country_code, formatted_phone
`

type UpdateCustomerNotesParams struct {
	ID    int64          `json:"id"`
	Notes sql.NullString `json:"notes"`
}

func (q *Queries) UpdateCustomerNotes(ctx context.Context, arg UpdateCustomerNotesParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, updateCustomerNotes, arg.ID, arg.Notes)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Notes,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.ContactKey,
		&i.CountryCode,
		&i.FormattedPhone,
	)
	return i, err
}
