// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package jahitin_be_db

import (
	"context"
	"database/sql"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    name, user_id, phone, notes
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, name, phone, notes, updated_at, created_at
`

type CreateCustomerParams struct {
	Name   string         `json:"name"`
	UserID int64          `json:"user_id"`
	Phone  sql.NullString `json:"phone"`
	Notes  sql.NullString `json:"notes"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.Name,
		arg.UserID,
		arg.Phone,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Notes,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomersByUserID = `-- name: ListCustomersByUserID :many
SELECT id, user_id, name, phone, notes, updated_at, created_at FROM customers
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCustomersByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCustomersByUserID(ctx context.Context, arg ListCustomersByUserIDParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomersByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.Notes,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
