// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package jahitin_be_db

import (
	"database/sql"
	"time"
)

type ClothesCategory struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Customer struct {
	ID             int64          `json:"id"`
	UserID         int64          `json:"user_id"`
	Name           string         `json:"name"`
	Phone          sql.NullString `json:"phone"`
	Notes          sql.NullString `json:"notes"`
	UpdatedAt      time.Time      `json:"updated_at"`
	CreatedAt      time.Time      `json:"created_at"`
	ContactKey     sql.NullString `json:"contact_key"`
	CountryCode    sql.NullString `json:"country_code"`
	FormattedPhone sql.NullString `json:"formatted_phone"`
}

type NotificationLog struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"user_id"`
	OrderID          sql.NullInt64  `json:"order_id"`
	OrderItemID      sql.NullInt64  `json:"order_item_id"`
	DeviceID         sql.NullString `json:"device_id"`
	NotificationType string         `json:"notification_type"`
	Status           string         `json:"status"`
	Message          sql.NullString `json:"message"`
	UpdatedAt        time.Time      `json:"updated_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

type Order struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	UserID      int64          `json:"user_id"`
	CustomerID  int64          `json:"customer_id"`
	Deadline    sql.NullTime   `json:"deadline"`
	Status      string         `json:"status"`
	SharingCode sql.NullString `json:"sharing_code"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CreatedAt   time.Time      `json:"created_at"`
	FinishedAt  sql.NullTime   `json:"finished_at"`
}

type OrderItem struct {
	ID                int64          `json:"id"`
	OrderID           int64          `json:"order_id"`
	CategoryID        sql.NullInt64  `json:"category_id"`
	ServiceTypeID     sql.NullInt64  `json:"service_type_id"`
	ClothesFor        string         `json:"clothes_for"`
	CustomServiceName sql.NullString `json:"custom_service_name"`
	Notes             sql.NullString `json:"notes"`
	Price             int64          `json:"price"`
	Status            string         `json:"status"`
	UpdatedAt         time.Time      `json:"updated_at"`
	CreatedAt         time.Time      `json:"created_at"`
	FinishedAt        sql.NullTime   `json:"finished_at"`
}

type ServiceType struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	DeviceID     sql.NullString `json:"device_id"`
	UserType     string         `json:"user_type"`
	Phone        sql.NullString `json:"phone"`
	UpdatedAt    time.Time      `json:"updated_at"`
	CreatedAt    time.Time      `json:"created_at"`
}
