// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package jahitin_be_db

import (
	"context"
	"database/sql"
	"time"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id, name, customer_id, deadline
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, user_id, customer_id, deadline, status, sharing_code, updated_at, created_at, finished_at
`

type CreateOrderParams struct {
	UserID     int64        `json:"user_id"`
	Name       string       `json:"name"`
	CustomerID int64        `json:"customer_id"`
	Deadline   sql.NullTime `json:"deadline"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.Name,
		arg.CustomerID,
		arg.Deadline,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CustomerID,
		&i.Deadline,
		&i.Status,
		&i.SharingCode,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishOrderStatus = `-- name: FinishOrderStatus :one
UPDATE orders SET status = 'completed', finished_at = NOW() WHERE id = $1 RETURNING id, name, user_id, customer_id, deadline, status, sharing_code, updated_at, created_at, finished_at
`

func (q *Queries) FinishOrderStatus(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, finishOrderStatus, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CustomerID,
		&i.Deadline,
		&i.Status,
		&i.SharingCode,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getOrderDetailsByOrderID = `-- name: GetOrderDetailsByOrderID :one
SELECT o.id, o.name,
  o.deadline,
  o.status,
  o.user_id,
  c.id AS customer_id,
  c.name AS customer_name,
  c.phone AS customer_phone
FROM orders o
JOIN customers c ON o.customer_id = c.id
WHERE o.id = $1
`

type GetOrderDetailsByOrderIDRow struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Deadline      sql.NullTime   `json:"deadline"`
	Status        string         `json:"status"`
	UserID        int64          `json:"user_id"`
	CustomerID    int64          `json:"customer_id"`
	CustomerName  string         `json:"customer_name"`
	CustomerPhone sql.NullString `json:"customer_phone"`
}

func (q *Queries) GetOrderDetailsByOrderID(ctx context.Context, id int64) (GetOrderDetailsByOrderIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderDetailsByOrderID, id)
	var i GetOrderDetailsByOrderIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Deadline,
		&i.Status,
		&i.UserID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
	)
	return i, err
}

const listUserOrdersFiltered = `-- name: ListUserOrdersFiltered :many
SELECT o.id, o.name, o.user_id, o.customer_id, o.deadline, o.status, o.sharing_code, o.updated_at, o.created_at, o.finished_at, c.id AS customer_id, c.name AS customer_name
FROM orders o
JOIN customers c ON c.id = o.customer_id
WHERE o.user_id = $1
  AND (NULLIF($2, '')::text IS NULL OR o.status = $2)
  AND (
    NULLIF($3, '')::text IS NULL OR
    o.name ILIKE '%' || $3 || '%' OR
    c.name ILIKE '%' || $3 || '%'
  )
ORDER BY o.created_at DESC
LIMIT $4 OFFSET $5
`

type ListUserOrdersFilteredParams struct {
	UserID  int64       `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListUserOrdersFilteredRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	UserID       int64          `json:"user_id"`
	CustomerID   int64          `json:"customer_id"`
	Deadline     sql.NullTime   `json:"deadline"`
	Status       string         `json:"status"`
	SharingCode  sql.NullString `json:"sharing_code"`
	UpdatedAt    time.Time      `json:"updated_at"`
	CreatedAt    time.Time      `json:"created_at"`
	FinishedAt   sql.NullTime   `json:"finished_at"`
	CustomerID_2 int64          `json:"customer_id_2"`
	CustomerName string         `json:"customer_name"`
}

func (q *Queries) ListUserOrdersFiltered(ctx context.Context, arg ListUserOrdersFilteredParams) ([]ListUserOrdersFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserOrdersFiltered,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOrdersFilteredRow{}
	for rows.Next() {
		var i ListUserOrdersFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CustomerID,
			&i.Deadline,
			&i.Status,
			&i.SharingCode,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.CustomerID_2,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders set status = $1
WHERE id = $2
RETURNING id, name, user_id, customer_id, deadline, status, sharing_code, updated_at, created_at, finished_at
`

type UpdateOrderStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CustomerID,
		&i.Deadline,
		&i.Status,
		&i.SharingCode,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}
