// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_item.sql

package jahitin_be_db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id, category_id, service_type_id, clothes_for, custom_service_name, notes, price, status
) VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, order_id, category_id, service_type_id, clothes_for, custom_service_name, notes, price, status, updated_at, created_at, finished_at
`

type CreateOrderItemParams struct {
	OrderID           int64          `json:"order_id"`
	CategoryID        sql.NullInt64  `json:"category_id"`
	ServiceTypeID     sql.NullInt64  `json:"service_type_id"`
	ClothesFor        string         `json:"clothes_for"`
	CustomServiceName sql.NullString `json:"custom_service_name"`
	Notes             sql.NullString `json:"notes"`
	Price             int64          `json:"price"`
	Status            string         `json:"status"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.CategoryID,
		arg.ServiceTypeID,
		arg.ClothesFor,
		arg.CustomServiceName,
		arg.Notes,
		arg.Price,
		arg.Status,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CategoryID,
		&i.ServiceTypeID,
		&i.ClothesFor,
		&i.CustomServiceName,
		&i.Notes,
		&i.Price,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listOrderItemsByMultipleOrderIDs = `-- name: ListOrderItemsByMultipleOrderIDs :many
SELECT id, order_id, category_id, service_type_id, clothes_for, custom_service_name, notes, price, status, updated_at, created_at, finished_at FROM order_items
WHERE order_id = ANY($1::int[])
`

func (q *Queries) ListOrderItemsByMultipleOrderIDs(ctx context.Context, dollar_1 []int32) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByMultipleOrderIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CategoryID,
			&i.ServiceTypeID,
			&i.ClothesFor,
			&i.CustomServiceName,
			&i.Notes,
			&i.Price,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, category_id, service_type_id, clothes_for, custom_service_name, notes, price, status, updated_at, created_at, finished_at FROM order_items
WHERE order_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrderItemsByOrderIDParams struct {
	OrderID int64 `json:"order_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, arg ListOrderItemsByOrderIDParams) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByOrderID, arg.OrderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CategoryID,
			&i.ServiceTypeID,
			&i.ClothesFor,
			&i.CustomServiceName,
			&i.Notes,
			&i.Price,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
