// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_item.sql

package jahitin_be_db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id, category_id, service_type_id, clothes_for, custom_service_name, notes, price
) VALUES
    ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, order_id, category_id, service_type_id, clothes_for, custom_service_name, notes, price, status, updated_at, created_at, finished_at
`

type CreateOrderItemParams struct {
	OrderID           int64          `json:"order_id"`
	CategoryID        sql.NullInt64  `json:"category_id"`
	ServiceTypeID     sql.NullInt64  `json:"service_type_id"`
	ClothesFor        string         `json:"clothes_for"`
	CustomServiceName sql.NullString `json:"custom_service_name"`
	Notes             sql.NullString `json:"notes"`
	Price             int64          `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.CategoryID,
		arg.ServiceTypeID,
		arg.ClothesFor,
		arg.CustomServiceName,
		arg.Notes,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CategoryID,
		&i.ServiceTypeID,
		&i.ClothesFor,
		&i.CustomServiceName,
		&i.Notes,
		&i.Price,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listOrderItemsByMultipleOrderIDs = `-- name: ListOrderItemsByMultipleOrderIDs :many
SELECT
    oi.id,
    oi.order_id,
    oi.category_id,
    oi.service_type_id,
    oi.clothes_for,
    oi.custom_service_name,
    oi.notes,
    oi.price,
    oi.status,
    oi.updated_at,
    oi.created_at,
    oi.finished_at,
    cc.name AS category_name,
    st.name AS service_type_name
FROM order_items oi
LEFT JOIN clothes_categories cc ON cc.id = oi.category_id
LEFT JOIN service_types st ON st.id = oi.service_type_id
WHERE oi.order_id = ANY($1::int[])
`

type ListOrderItemsByMultipleOrderIDsRow struct {
	ID                int64          `json:"id"`
	OrderID           int64          `json:"order_id"`
	CategoryID        sql.NullInt64  `json:"category_id"`
	ServiceTypeID     sql.NullInt64  `json:"service_type_id"`
	ClothesFor        string         `json:"clothes_for"`
	CustomServiceName sql.NullString `json:"custom_service_name"`
	Notes             sql.NullString `json:"notes"`
	Price             int64          `json:"price"`
	Status            string         `json:"status"`
	UpdatedAt         time.Time      `json:"updated_at"`
	CreatedAt         time.Time      `json:"created_at"`
	FinishedAt        sql.NullTime   `json:"finished_at"`
	CategoryName      sql.NullString `json:"category_name"`
	ServiceTypeName   sql.NullString `json:"service_type_name"`
}

func (q *Queries) ListOrderItemsByMultipleOrderIDs(ctx context.Context, dollar_1 []int32) ([]ListOrderItemsByMultipleOrderIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByMultipleOrderIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsByMultipleOrderIDsRow{}
	for rows.Next() {
		var i ListOrderItemsByMultipleOrderIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CategoryID,
			&i.ServiceTypeID,
			&i.ClothesFor,
			&i.CustomServiceName,
			&i.Notes,
			&i.Price,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.CategoryName,
			&i.ServiceTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT cc.id, cc.name, cc.created_at, st.id, st.name, st.created_at, oi.id, oi.order_id, oi.category_id, oi.service_type_id, oi.clothes_for, oi.custom_service_name, oi.notes, oi.price, oi.status, oi.updated_at, oi.created_at, oi.finished_at FROM order_items oi
JOIN clothes_categories cc ON cc.id = oi.category_id
JOIN service_types st ON st.id = oi.service_type_id
WHERE order_id = $1
ORDER BY oi.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrderItemsByOrderIDParams struct {
	OrderID int64 `json:"order_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type ListOrderItemsByOrderIDRow struct {
	ID                int64          `json:"id"`
	Name              string         `json:"name"`
	CreatedAt         time.Time      `json:"created_at"`
	ID_2              int64          `json:"id_2"`
	Name_2            string         `json:"name_2"`
	CreatedAt_2       time.Time      `json:"created_at_2"`
	ID_3              int64          `json:"id_3"`
	OrderID           int64          `json:"order_id"`
	CategoryID        sql.NullInt64  `json:"category_id"`
	ServiceTypeID     sql.NullInt64  `json:"service_type_id"`
	ClothesFor        string         `json:"clothes_for"`
	CustomServiceName sql.NullString `json:"custom_service_name"`
	Notes             sql.NullString `json:"notes"`
	Price             int64          `json:"price"`
	Status            string         `json:"status"`
	UpdatedAt         time.Time      `json:"updated_at"`
	CreatedAt_3       time.Time      `json:"created_at_3"`
	FinishedAt        sql.NullTime   `json:"finished_at"`
}

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, arg ListOrderItemsByOrderIDParams) ([]ListOrderItemsByOrderIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByOrderID, arg.OrderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsByOrderIDRow{}
	for rows.Next() {
		var i ListOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ID_2,
			&i.Name_2,
			&i.CreatedAt_2,
			&i.ID_3,
			&i.OrderID,
			&i.CategoryID,
			&i.ServiceTypeID,
			&i.ClothesFor,
			&i.CustomServiceName,
			&i.Notes,
			&i.Price,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt_3,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
