// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package jahitin_be_db

import (
	"context"
	"database/sql"
	"time"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id, name, customer_id, deadline, status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, user_id, customer_id, deadline, status, sharing_code, updated_at, created_at, finished_at
`

type CreateOrderParams struct {
	UserID     int64        `json:"user_id"`
	Name       string       `json:"name"`
	CustomerID int64        `json:"customer_id"`
	Deadline   sql.NullTime `json:"deadline"`
	Status     string       `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.Name,
		arg.CustomerID,
		arg.Deadline,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CustomerID,
		&i.Deadline,
		&i.Status,
		&i.SharingCode,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getOrderDetailsByOrderID = `-- name: GetOrderDetailsByOrderID :one
SELECT o.id, o.name, o.deadline, o.status, c.id, c.name AS customer_name, c.phone AS customer_phone FROM orders o
JOIN customers c ON o.customer_id = c.id
WHERE o.id = $1
`

type GetOrderDetailsByOrderIDRow struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Deadline      sql.NullTime   `json:"deadline"`
	Status        string         `json:"status"`
	ID_2          int64          `json:"id_2"`
	CustomerName  string         `json:"customer_name"`
	CustomerPhone sql.NullString `json:"customer_phone"`
}

func (q *Queries) GetOrderDetailsByOrderID(ctx context.Context, id int64) (GetOrderDetailsByOrderIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderDetailsByOrderID, id)
	var i GetOrderDetailsByOrderIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Deadline,
		&i.Status,
		&i.ID_2,
		&i.CustomerName,
		&i.CustomerPhone,
	)
	return i, err
}

const listOrdersByUserId = `-- name: ListOrdersByUserId :many
SELECT id, name, user_id, customer_id, deadline, status, sharing_code, updated_at, created_at, finished_at FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserIdParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrdersByUserId(ctx context.Context, arg ListOrdersByUserIdParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CustomerID,
			&i.Deadline,
			&i.Status,
			&i.SharingCode,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersHeaderByUserID = `-- name: ListOrdersHeaderByUserID :many
SELECT o.id, o.name, o.user_id, o.customer_id, o.deadline, o.status, o.sharing_code, o.updated_at, o.created_at, o.finished_at, oi.id, oi.order_id, oi.category_id, oi.service_type_id, oi.clothes_for, oi.custom_service_name, oi.notes, oi.price, oi.status, oi.updated_at, oi.created_at, oi.finished_at, c.name AS customer_name FROM orders o
JOIN order_items oi ON o.id = oi.order_id 
JOIN customers c ON o.customer_id = c.id
WHERE o.user_id = $1
ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersHeaderByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListOrdersHeaderByUserIDRow struct {
	ID                int64          `json:"id"`
	Name              string         `json:"name"`
	UserID            int64          `json:"user_id"`
	CustomerID        int64          `json:"customer_id"`
	Deadline          sql.NullTime   `json:"deadline"`
	Status            string         `json:"status"`
	SharingCode       sql.NullString `json:"sharing_code"`
	UpdatedAt         time.Time      `json:"updated_at"`
	CreatedAt         time.Time      `json:"created_at"`
	FinishedAt        sql.NullTime   `json:"finished_at"`
	ID_2              int64          `json:"id_2"`
	OrderID           int64          `json:"order_id"`
	CategoryID        sql.NullInt64  `json:"category_id"`
	ServiceTypeID     sql.NullInt64  `json:"service_type_id"`
	ClothesFor        string         `json:"clothes_for"`
	CustomServiceName sql.NullString `json:"custom_service_name"`
	Notes             sql.NullString `json:"notes"`
	Price             int64          `json:"price"`
	Status_2          string         `json:"status_2"`
	UpdatedAt_2       time.Time      `json:"updated_at_2"`
	CreatedAt_2       time.Time      `json:"created_at_2"`
	FinishedAt_2      sql.NullTime   `json:"finished_at_2"`
	CustomerName      string         `json:"customer_name"`
}

func (q *Queries) ListOrdersHeaderByUserID(ctx context.Context, arg ListOrdersHeaderByUserIDParams) ([]ListOrdersHeaderByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersHeaderByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersHeaderByUserIDRow{}
	for rows.Next() {
		var i ListOrdersHeaderByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CustomerID,
			&i.Deadline,
			&i.Status,
			&i.SharingCode,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.ID_2,
			&i.OrderID,
			&i.CategoryID,
			&i.ServiceTypeID,
			&i.ClothesFor,
			&i.CustomServiceName,
			&i.Notes,
			&i.Price,
			&i.Status_2,
			&i.UpdatedAt_2,
			&i.CreatedAt_2,
			&i.FinishedAt_2,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
