// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package jahitin_be_db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateBaseUser(ctx context.Context, arg CreateBaseUserParams) (User, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteOrderItemByOrderID(ctx context.Context, orderID int64) error
	FinishOrderStatus(ctx context.Context, id int64) (Order, error)
	GetCustomerByID(ctx context.Context, id int64) (Customer, error)
	GetCustomerByUserIDAndContactKey(ctx context.Context, arg GetCustomerByUserIDAndContactKeyParams) (Customer, error)
	GetOrderDetailsByOrderID(ctx context.Context, id int64) (GetOrderDetailsByOrderIDRow, error)
	GetUserByDeviceID(ctx context.Context, deviceID sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListClothesCategories(ctx context.Context) ([]ClothesCategory, error)
	ListCustomersByUserID(ctx context.Context, arg ListCustomersByUserIDParams) ([]Customer, error)
	ListCustomersByUserIDAndName(ctx context.Context, arg ListCustomersByUserIDAndNameParams) ([]Customer, error)
	ListOrderItemsByMultipleOrderIDs(ctx context.Context, dollar_1 []int32) ([]ListOrderItemsByMultipleOrderIDsRow, error)
	ListOrderItemsByOrderID(ctx context.Context, arg ListOrderItemsByOrderIDParams) ([]ListOrderItemsByOrderIDRow, error)
	ListServiceTypes(ctx context.Context) ([]ServiceType, error)
	ListUserOrdersFiltered(ctx context.Context, arg ListUserOrdersFilteredParams) ([]ListUserOrdersFilteredRow, error)
	SeedClothesCategories(ctx context.Context) ([]ClothesCategory, error)
	SeedServiceTypes(ctx context.Context) ([]ServiceType, error)
	UpdateCustomerNotes(ctx context.Context, arg UpdateCustomerNotesParams) (Customer, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
