// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package jahitin_be_db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateBaseUser(ctx context.Context, arg CreateBaseUserParams) (User, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetCustomerByID(ctx context.Context, id int64) (Customer, error)
	GetOrderDetailsByOrderID(ctx context.Context, id int64) (GetOrderDetailsByOrderIDRow, error)
	GetUserByDeviceID(ctx context.Context, deviceID sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListClothesCategories(ctx context.Context) ([]ClothesCategory, error)
	ListCustomersByUserID(ctx context.Context, arg ListCustomersByUserIDParams) ([]Customer, error)
	ListCustomersByUserIDAndName(ctx context.Context, arg ListCustomersByUserIDAndNameParams) ([]Customer, error)
	ListOrderItemsByMultipleOrderIDs(ctx context.Context, dollar_1 []int32) ([]OrderItem, error)
	ListOrderItemsByOrderID(ctx context.Context, arg ListOrderItemsByOrderIDParams) ([]OrderItem, error)
	ListServiceTypes(ctx context.Context) ([]ServiceType, error)
	ListUserOrdersFiltered(ctx context.Context, arg ListUserOrdersFilteredParams) ([]ListUserOrdersFilteredRow, error)
	SeedClothesCategories(ctx context.Context) ([]ClothesCategory, error)
	SeedServiceTypes(ctx context.Context) ([]ServiceType, error)
	UpdateCustomerNotes(ctx context.Context, arg UpdateCustomerNotesParams) (Customer, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
