// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package jahitin_be_db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateBaseUser(ctx context.Context, arg CreateBaseUserParams) (User, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetOrderDetailsByOrderID(ctx context.Context, id int64) (GetOrderDetailsByOrderIDRow, error)
	GetUserByDeviceID(ctx context.Context, deviceID sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListClothesCategories(ctx context.Context) ([]ClothesCategory, error)
	ListCustomersByUserID(ctx context.Context, arg ListCustomersByUserIDParams) ([]Customer, error)
	ListOrderItemsByOrderID(ctx context.Context, arg ListOrderItemsByOrderIDParams) ([]OrderItem, error)
	ListOrdersByUserId(ctx context.Context, arg ListOrdersByUserIdParams) ([]Order, error)
	ListOrdersHeaderByUserID(ctx context.Context, arg ListOrdersHeaderByUserIDParams) ([]ListOrdersHeaderByUserIDRow, error)
	ListServiceTypes(ctx context.Context) ([]ServiceType, error)
	SeedClothesCategories(ctx context.Context) ([]ClothesCategory, error)
	SeedServiceTypes(ctx context.Context) ([]ServiceType, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
