// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_type.sql

package jahitin_be_db

import (
	"context"
)

const listServiceTypes = `-- name: ListServiceTypes :many
SELECT
    id, name, created_at
FROM
    service_types
ORDER BY
    name ASC
`

func (q *Queries) ListServiceTypes(ctx context.Context) ([]ServiceType, error) {
	rows, err := q.db.QueryContext(ctx, listServiceTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceType{}
	for rows.Next() {
		var i ServiceType
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedServiceTypes = `-- name: SeedServiceTypes :many
INSERT INTO
    service_types (name)
VALUES
    ('Jahit Baju'),
    ('Kecilkan'),
    ('Besarkan'),
    ('Pendekkan'),
    ('Resleting'),
    ('Ganti Kancing'),
    ('Tambal'),
    ('Tambah Furing'),
    ('Ganti Tali'),
    ('Ganti Ritsleting'),
    ('Pasang Bed') RETURNING id, name, created_at
`

func (q *Queries) SeedServiceTypes(ctx context.Context) ([]ServiceType, error) {
	rows, err := q.db.QueryContext(ctx, seedServiceTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceType{}
	for rows.Next() {
		var i ServiceType
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
