// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package jahitin_be_db

import (
	"context"
	"database/sql"
)

const createBaseUser = `-- name: CreateBaseUser :one
INSERT INTO users (
    name, device_id, user_type, phone
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, username, email, password_hash, device_id, user_type, phone, updated_at, created_at
`

type CreateBaseUserParams struct {
	Name     string         `json:"name"`
	DeviceID sql.NullString `json:"device_id"`
	UserType string         `json:"user_type"`
	Phone    sql.NullString `json:"phone"`
}

func (q *Queries) CreateBaseUser(ctx context.Context, arg CreateBaseUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createBaseUser,
		arg.Name,
		arg.DeviceID,
		arg.UserType,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DeviceID,
		&i.UserType,
		&i.Phone,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name, username, email, password_hash, device_id, user_type, phone
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, username, email, password_hash, device_id, user_type, phone, updated_at, created_at
`

type CreateUserParams struct {
	Name         string         `json:"name"`
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	DeviceID     sql.NullString `json:"device_id"`
	UserType     string         `json:"user_type"`
	Phone        sql.NullString `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DeviceID,
		arg.UserType,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DeviceID,
		&i.UserType,
		&i.Phone,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByDeviceID = `-- name: GetUserByDeviceID :one
SELECT id, name, username, email, password_hash, device_id, user_type, phone, updated_at, created_at FROM users
WHERE device_id = $1
`

func (q *Queries) GetUserByDeviceID(ctx context.Context, deviceID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByDeviceID, deviceID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DeviceID,
		&i.UserType,
		&i.Phone,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, username, email, password_hash, device_id, user_type, phone, updated_at, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DeviceID,
		&i.UserType,
		&i.Phone,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, username = $3, email = $4, password_hash = $5, device_id = $6, user_type = $7, phone = $8
WHERE id = $1
RETURNING id, name, username, email, password_hash, device_id, user_type, phone, updated_at, created_at
`

type UpdateUserParams struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	DeviceID     sql.NullString `json:"device_id"`
	UserType     string         `json:"user_type"`
	Phone        sql.NullString `json:"phone"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DeviceID,
		arg.UserType,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DeviceID,
		&i.UserType,
		&i.Phone,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
